[package]
name = "rust-pastebin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.0"
rand = "0.8"
actix-files = "0.5"
serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
